sudo: required
services:
    - docker
    
before_install:
    - docker build -t carlosalonsogtz/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true carlosalonsogtz/docker-react npm run test

language: generic

after_success:
    - docker build -t carlosalonsogtz/multi-client ./client
    - docker build -t carlosalonsogtz/multi-nginx ./nginx
    - docker build -t carlosalonsogtz/multi-server ./server
    - docker build -t carlosalonsogtz/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push them to Docker hub.
    - docker-push carlosalonsogtz/multi-client
    - docker-push carlosalonsogtz/multi-nginx
    - docker-push carlosalonsogtz/multi-server
    - docker-push carlosalonsogtz/multi-worker